version: '3.8'

services:

  web:
    image: nginx
    restart: always
    depends_on:
      - open-webui
    ports:
      - 11080:80
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - home_gateway_net
    environment:
      TZ: Asia/Shanghai

  api:
    build:
      context: ./ # 指定 Dockerfile 的目录
      dockerfile: Dockerfile # 可选，明确指定 Dockerfile 名称，如果使用默认名称可省略
    ports:
      - "8000:8000" # 将容器的 8000 端口映射到主机的 8000 端口
    volumes:
      - ./:/app # 将本地的 app 目录挂载到容器的 /app 目录
    environment:
      - PYTHONUNBUFFERED=1 # 确保 Python 不缓冲输出
    command: uvicorn ai_main:app --host 0.0.0.0 --port 8000 # 启动命令

  milvus-standalone:
    image: milvusdb/milvus:v2.4.13-hotfix
    container_name: home_milvus_standalone
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - ../data/milvusDB/milvus:/var/lib/milvus
      - ../docker/milvusDB/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ../docker/milvusDB/user.yaml:/milvus/configs/user.yaml
    networks:
      - home_gateway_net
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    command: [ "milvus", "run", "standalone" ]
