version: '3.8'


name: mf-ai-cluster

networks:
  ai_cluster_net:
    driver: bridge

services:

  api:
    build:
      context: ./ # 指定 Dockerfile 的目录
      dockerfile: Dockerfile # 可选，明确指定 Dockerfile 名称，如果使用默认名称可省略
    image: mf-ai:v1
    ports:
      - "8000:8000" # 将容器的 8000 端口映射到主机的 8000 端口
    volumes:
      - ./api:/app # 将本地的 app 目录挂载到容器的 /app 目录
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # 启动命令
