version: '3.8'

services:
  web:
    build:
      context: ./  # 指定 Dockerfile 的目录
      dockerfile: Dockerfile # 可选，明确指定 Dockerfile 名称，如果使用默认名称可省略
    ports:
      - "8000:8000"  # 将容器的 8000 端口映射到主机的 8000 端口
    volumes:
      - ./:/app  # 将本地的 app 目录挂载到容器的 /app 目录
    environment:
      - PYTHONUNBUFFERED=1  # 确保 Python 不缓冲输出
    command: uvicorn ai_main:app --host 0.0.0.0 --port 8000  # 启动命令